# Site settings
title: DS4PS

description: >               # this means to ignore newlines until "baseurl:"
baseurl: ""                 # the subpath of your site, e.g. /blog/
url: "http://ds4ps.org"      # the base hostname & protocol for your site

github_username: lecy
email: 
twitter_username: username

header:
  - title: Getting Started
    url : /introducing
  - title: Careers
    url : /careers
  - title: Resources
    url : /resources   
  - title: Data
    url : /data
  - title: Community
    url : /discuss 
    
# Build settings
# markdown: redcarpet
# markdown_ext:  markdown,mkdown,mkdn,mkd,md

# redcarpet:
#   extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
